core/urls.py
from django.urls import path
from .views import (
    ItemDetailView,
    CheckoutView,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,
    AddCouponView,
    RequestRefundView
)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund')
]

core/models.py
from django.db.models.signals import post_save
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.shortcuts import reverse
from django_countries.fields import CountryField



CATEGORY_CHOICES = (
    ('A', 'Arboles'),
    ('F', 'Flores'),
    ('R', 'Rosas')
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)


class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(
        'Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"


def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)


post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/custom.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

{% include "navbar.html" %}

<body>

    <div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
    </div>

    {% block content %}
    {% endblock content %}

    {% block extra_body %}
    {% endblock %}
<br>
    {% include "footer.html" %}
    {% include "scripts.html" %}

    {% block extra_scripts %}
    {% endblock extra_scripts %}

</body>
</html>

templates/checkout.html
{% extends "base.html" %}


{% block content %}

  <main style="margin-top: -50px;"  class="central-custom2">
    <div class="container wow">
      <h2 class="my-5 h2 text-center txt-welcome">Confirmar Orden</h2>
      <div class="row">
        <div class="col-md-8 mb-4">
          <div class="card">
            <form method="" class="card-body">
              

              <h3>Dirección de entrega</h3>

              <div class='hideable_shipping_form'>

                <div class="md-form mb-5">
                  <input type='text' class='form-control' />
                  <label for="shipping_address" class="">Dirección</label>
                </div>

                

                <div class="row">
                  <div class="col-lg-4 col-md-6 mb-4">
                    <label for="shipping_zip">Codigo Postal</label>
                    <input type='text'  class='form-control' />
                    <div class="invalid-feedback">
                      Porfavor ingrese su Codigo Postal
                    </div>
                  </div>
                </div>

                
                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" name="set_default_shipping" id="set_default_shipping">
                  <label class="custom-control-label" for="set_default_shipping">Guardar como dirección de envio predeterminada</label>
                </div>

              </div>

              <hr>

              <h3>Opciones de pago</h3>

              <br>


              <div class="">
                
                  <div class="custom-control custom-radio">
                    <input type="radio" class="custon-control-input" required>
                    <label for="Paypal">Paypal</label>
                  </div>

                  <div class="custom-control custom-radio">
                    <input type="radio" class="custon-control-input" required>
                    <label for="Paypal">Tarjeta</label>
                  </div>
                  <br>
                  <input type="button" style="width: 400px; margin-left: 140px;" value="Continuar la compra" class="btn btn-primary btn-lg btn-block" onclick="pago()" >

                
              </div>

              <hr class="mb-4">
              
              <br>

            </form>

          </div>

        </div>

        <div class="col-md-4 mb-4">
          
        </div>

      </div>

    </div>
    <br>
    <br>
    <br>
  </main>

{% endblock content %}

{% block extra_scripts %}


<script>
  function pago() {
  alert("Compra Realizada");
  location.href="../";

}  
</script>
{% endblock extra_scripts %}

templates/footer.html
<footer class="page-footer text-center font-small mt-4 yellow">

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
        <a href="https://www.facebook.com/" target="_blank">
            <i class="fab fa-facebook-f dark-grey-text mr-3"></i>
        </a>

        <a href="https://twitter.com/" target="_blank">
            <i class="fab fa-twitter dark-grey-text mr-3"></i>
        </a>

        <a href="https://www.youtube.com/" target="_blank">
            <i class="fab fa-youtube dark-grey-text mr-3"></i>
        </a>


    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright dark-grey-text py-3">
        <a class="dark-grey-text" target="_blank">Floreria "El Paraiso"</a>
    </div>
    <!--/.Copyright-->

</footer>

templates/home.html
{% extends "base.html" %} {% block content %}
<main class="central-custom">
    <div class="container">
        <nav class="nav-productos">
            <div class="txt-welcome">
                <p>NUESTROS PRODUCTOS</p>
            </div>
        </nav>
        <!--/.Navbar-->

        <!--Section: Products v.3-->
        <section class="text-center mb-4">

            <div class="row wow fadeIn">

                {% for item in object_list %}
                <div class="col-lg-3 col-md-6 mb-4">

                    <div class="card">

                        <div class="view overlay">
                            <img src="{{ item.image.url }}" class="card-img-top">


                            <a href="{{ item.get_absolute_url }}">
                                <div class="mask rgba-white-slight"></div>
                            </a>
                        </div>

                        <div class="card-body text-center">
                            <a class="grey-text">
                                <h5>{{ item.get_category_display }}</h5>
                            </a>
                            <h5>
                                <strong>
                  <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                    <span class="badge badge-pill {{ item.get_label_display }}-color">Nuevo</span>
                  </a>
                </strong>
                            </h5>

                            <h4 class="font-weight-bold blue-text">
                                <strong>$
                  {% if item.discount_price %}
                  {{ item.discount_price }}0
                  {% else %}
                  {{ item.price }}0
                  {% endif %}
                </strong>
                            </h4>

                        </div>

                    </div>

                </div>
                {% endfor %}
            </div>

        </section>
        

    {% if is_paginated %}
        <nav class="d-flex justify-content-center wow fadeIn">
          <ul class="pagination pg-blue">

            {% if page_obj.has_previous %}
            <li style="color: white;" class="page-item">
              <a style="color: white;" class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Anterior</span>
              </a>
            </li>
            {% endif %}

            <li style="color: white;" class="page-item active">
              <a style="color: white;" class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
                <span class="sr-only">(current)</span>
              </a>
            </li>

            {% if page_obj.has_next %}
            <li style="color: white;" class="page-item">
              <a style="color: white;" class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Siguiente</span>
              </a>
            </li>
            {% endif %}
          </ul>
        </nav>
        {% endif %}
        <br>
    </div>
</main>

{% endblock content %}

templates/navbar.html
{% load cart_template_tags %} {% load staticfiles %}

<nav class="navbar fixed-top navbar-expand-lg navbar-light yellow">
    <div class="container">

        <!-- Brand -->
        <a class="" href="/" href="/">

            <img class="logo" src="{% static 'img/logo-floreria.png' %}" alt="">

        </a>

        <!-- Collapse -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

        <!-- Links -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <!-- Left -->
            <ul class="navbar-nav mr-auto">
                {% comment %}
                <li class="nav-item active">
                    <a class="nav-link waves-effect" href="/">
          <span class="sr-only">(current)</span>
        </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link waves-effect" href="/checkout">
          Checkout</a>
                </li> {% endcomment %}
            </ul>

            <!-- Right -->
            <ul class="navbar-nav nav-flex-icons">
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a href="{% url 'core:order-summary' %}" class="nav-link waves-effect">
                        <span class="badge red z-depth-1 mr-1"> {{ request.user}} </span>
                        <i class="fas fa-shopping-cart"></i>
                        <span class="clearfix d-none d-sm-inline-block"> Carrito </span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
                        <span class="clearfix d-none d-sm-inline-block"> Cerrar Sesión </span>
                    </a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link waves-effect" href="{% url 'account_login' %}">
                        <span class="clearfix d-none d-sm-inline-block"> Iniciar Sesión </span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
                        <span class="clearfix d-none d-sm-inline-block"> Regístrate </span>
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>

    </div>
</nav>

templates/order_snippet.html
<div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
    <span style="color: white" class="">Tu carrito</span>
    <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
    {% for order_item in order.items.all %}
    <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
        <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
        
        </div>
        <span class="text-muted">${{ order_item.get_final_price }}0</span>
    </li>
    {% endfor %}
    {% if order.coupon %}
    <li class="list-group-item d-flex justify-content-between bg-light">
        <div class="text-success">
        <h6 class="my-0">Promo code</h6>
        <small>{{ order.coupon.code }}</small>
        </div>
        <span class="text-success">-${{ order.coupon.amount }}</span>
    </li>
    {% endif %}
    <li class="list-group-item d-flex justify-content-between">
        <span>Total </span>
        <strong>${{ order.get_total }}0</strong>
    </li>
    </ul>
</div>

templates/order_summary.html
{% extends "base.html" %}

{% block content %}

<style>
    .page-footer{
        position: fixed; left: 0px; bottom: 0px; width: 100%; 
    }
    .main-custom{
        margin-top: -20px;
    }
    
</style>
  <main class="central-custom2 main-custom">
    <div class="container">

    <div class="table-responsive text-nowrap">
    <h2 class="txt-welcome">Carrito</h2>
    <table class="table">
        <thead>
        <tr>
            <th class="txt-welcome2" scope="col">#</th>
            <th class="txt-welcome2" scope="col">Producto</th>
            <th class="txt-welcome2" scope="col">Precio</th>
            <th class="txt-welcome2" scope="col">Cantidad</th>
            <th class="txt-welcome2" scope="col">Total</th>
        </tr>
        </thead>
        <tbody class="txt-welcome2">
        {% for order_item in object.items.all %}
        <tr>
            <th class="txt-welcome2" scope="row">{{ forloop.counter }}</th>
            <td>{{ order_item.item.title }}</td>
            <td>{{ order_item.item.price }}</td>
            <td>
                <a style="color: white" href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a>
                {{ order_item.quantity }}
                <a style="color: white" href="{% url 'core:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-2"></i></a>
            </td>
            <td>
            {% if order_item.item.discount_price %}
                ${{ order_item.get_total_discount_item_price }}
                <span class="badge badge-primary">Saving ${{ order_item.get_amount_saved }}</span>
            {% else %}
                ${{ order_item.get_total_item_price }}
            {% endif %}
            <a style='color: white;' href="{% url 'core:remove-from-cart' order_item.item.slug %}">
                <i class="fas fa-trash float-right"></i>
            </a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan='5'>El carrito esta vacio</td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-primary float-right' href='/'>Continuar comprando</a>
            </td>
        </tr>
        {% endfor %}
        {% if object.coupon %}
        <tr>
            <td colspan="4"><b>Coupon</b></td>
            <td><b>-${{ object.coupon.amount }}</b></td>
        </tr>
        {% endif %}
        {% if object.get_total %}
        <tr>
            <td colspan="4"><b>Order Total</b></td>
            <td><b>${{ object.get_total }}</b></td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-warning float-right ml-2' href='/checkout/'>Proceder al pago</a>
            <a class='btn btn-primary float-right' href='/'>Continuar comprando</a>
            </td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
<br>
    </div>

    </div>
  </main>

{% endblock content %}

templates/product.html
{% extends "base.html" %} {% block content %}

<main class="central-custom-productos">

    <div class="container white-text mt-5 txt-productos">

        <h1>{{ object.title }}</h1>

        <!--Grid row-->
        <div class="row wow fadeIn">



            <!--Grid column-->
            <div class="col-md-6 mb-4">

                <img class="img-ventas" src="{{ object.image.url }}" class="card-img-top">
            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-md-6 mb-4">


                <!--Content-->
                <div class="p-4 txt-descripcion">

                    <div class="mb-3">
                        <a>
                            <span class="badge purple mr-1">{{ object.get_category_display }}</span>
                        </a>
                    </div>

                    <p class="lead txt-precio">
                        {% if object.discount_price %}0
                        <span class="mr-1 ">
              <del>${{ object.price }}</del>
            </span>
                        <span>${{ object.discount_price }}0</span> {% else %}
                        <span>${{ object.price }}0</span> {% endif %}
                    </p>

                    <p class="lead font-weight-bold">Descripción</p>

                    <p>{{ object.description }}</p>

                    {% comment %}
                    <form class="d-flex justify-content-left">
                        <!-- Default input -->
                        <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
                        <button class="btn btn-primary btn-md my-0 p" type="submit">
              Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </button>

                    </form> {% endcomment %}
                    <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">
            Añadir al carrito
            <i class="fas fa-shopping-cart ml-1"></i>
          </a>


                </div>
                <!--Content-->

            </div>
            <!--Grid column-->

        </div>
        <!--Grid row-->

        <br><br><br>


</main>

{% endblock content %}

templates/request_refund.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <main>
    <div class="container">

    <h2>Request Refund</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class='btn btn-primary'>Submit</button>
    </form>

    </div>
  </main>

{% endblock content %}

templates/scripts.html
{% load static %}
  
<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
  // Animations initialization
  new WOW().init();

</script>